blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns =[
    path('', views.lista_postagem, name='lista_postagem'),
    path('<int:ano>/<int:mes>/<int:dia>/<slug:rotulo>/', views.detalhe_postagem, name='detalhe_postagem'),
    path('<int:post_id>/compartilhar/', views.compartilhar_postagens, name='compartilhar_postagens'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class GerenciarPostagem(models.Manager):
    def get_queryset(self):
        return super (GerenciarPostagem,self).get_queryset().filter(status='publicado')


class Postagem(models.Model):
    STATUS_CHOICE = (('rascunho', 'Rascunho'), ('publicado', 'Publicado'))

    titulo = models.CharField(max_length=250)
    rotulo = models.SlugField(max_length=250, unique_for_date='data_publicacao')
    autor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_postagem')
    mensagem = models.TextField()
    data_publicacao = models.DateTimeField(default=timezone.now)
    data_criacao = models.DateTimeField(auto_now_add=True)
    data_atualizacao = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICE, default='rascunho')

    objects = models.Manager()
    publicado = GerenciarPostagem()

    def get_absolute_url(self):
        return reverse('blog:detalhe_postagem', 
                        args=[self.data_publicacao.year,
                        self.data_publicacao.month, 
                        self.data_publicacao.day,
                        self.rotulo])


    class Meta:
        ordering = ("-data_publicacao",)

    def __str__(self):
        return self.titulo

class Comentarios(models.Model):
    post = models.ForeignKey(Postagem, on_delete=models.CASCADE, related_name='comentarios')
    nome = models.CharField(max_length=80)
    email = models.EmailField()
    mensagem = models.TextField()
    data_criacao = models.DateTimeField(auto_now_add=True)
    data_atualizacao = models.DateTimeField(auto_now=True)
    ativo = models.BooleanField(default=True)

    class Meta:
        ordering = ('data_criacao', )

    def __str__(self):
        return f'Comentado por {self.nome} no {self.post}'

blog/forms.py
from django import forms
from django.forms import ModelForm
from .models import Comentarios

class FormularioPostEmail(forms.Form):
    nome = forms.CharField(max_length=25)
    email = forms.EmailField()
    para = forms.EmailField()
    comentarios = forms.CharField(required=False, widget=forms.Textarea)

class FormularioComentarios(ModelForm):
    class Meta:
        model = Comentarios
        fields = ['nome', 'email', 'mensagem']

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import *
from django.core.mail import send_mail

def lista_postagem(request):
    lista_objetos = Postagem.publicado.all()
    paginacao = Paginator(lista_objetos, 3)
    pagina = request.GET.get('page')

    try:
        posts = paginacao.page(pagina)
    except PageNotAnInteger:
        posts = paginacao.page(1)
    except EmptyPage:
        posts = paginacao.page(paginacao.num_pages)
    
    return render(request, 'blog/postagem/lista.html', {'pagina': pagina, 'posts':posts})


def detalhe_postagem(request, ano, mes, dia, rotulo):
    post = get_object_or_404(Postagem, rotulo= rotulo, 
                            status = 'publicado', 
                            data_publicacao__year = ano,
                            data_publicacao__month = mes, 
                            data_publicacao__day = dia)
    return render(request, 'blog/postagem/detalhe.html', { 'post' : post})
    comentarios = post.comentarios.filter(ativo=True)

    novo_comentario = None

    if request.method == 'POST':
        forulario_cometario = forulario_cometario(data=request.POST)

        if forulario_cometario.is_valid():
            novo_comentario = forulario_cometario.save(conmint=False)
            novo_comentario.post = post
            novo_comentario.save()
        else:
            forulario_cometario = FormularioComentarios()
        
        return render(request, 'blog/postagem/detalhe.html', { 'post' : post,
                                                            'comentarios': comentarios,
                                                            'novo_comentario': novo_comentario,
                                                            'formulario_comentario': formulario_comentario})


def compartilhar_postagem(request, post_id):
    post = get_object_or_404(Postagem, id=post_id, status='publicado')
    sent = False

    if request.method == 'POST':
        form = FormularioPostEmail(request.POST)

        if form.is_valed():
            
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            assunto = f"{cd['nome']} recomendado que você leia" f"{ post.titulo }"
            mensagem = f"Leia {post.titulo} em {post_url}\n\n" f"{cd['nome']}\'s comentarios: {cd ['comentarios']}"
            send_mail(assunto, mensagem, 'pyhton.django@gmail.com', [cd['para']])
            sent = True
    
    else:
        form = FormularioPostEmail()

        return render(request, 'blog/postagem/compartilhar.html', {'post':post, 'form':form, 'sent':sent})

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="{% static "css/blog.css" %}" rel="stylesheet">

</head>
<body>
    <div id="content">
        {% block content %}
        
        {% endblock %}
    </div>

    <div id="sidebar">
        <h2>Meu blog</h2>
        <p> este é meu blog.</p>
    </div>
</body>
</html>

blog/templates/blog/postagem/compartilhar.html
{% extends 'blog/base.html' %}


{% block title %} Compartilhar Postagens {% endblock title %}
    

{% block content %}

    {% if sent %}
        <h1>E-mail enviado com sucesso</h1>
        <p>{{ post.titulo }} foi envidada com sucesso para {{ form.cleaned_data.para }}</p>
    
    {% else %}
        <h1>Compartilhado {{ post.titulo }} por e-mail</h1>   

        <form method="post">

            {{ form.as_p }}     <!-- Renderizar o formulario como paragrafo -->
            {% csrf_token %}    <!-- Criação de um codico de proteção de ataques -->

            <input type="submit" value="Enviar e-mail">

        </form>
    
    {% endif %}
         
{% endblock content %}
    

blog/templates/blog/postagem/detalhe.html
{% extends "blog/base.html" %}

{% block title%} {{ post.titulo}} {% endblock %}

{% block content%}
<h1> {{ post.titulo }}</h1>
<p class="data">
    Publicado em {{ post.data_publicacao }} por {{ post.autor }}
</p>

{{ post.mensagem|linebreaks }}

<p>
    <a href="{% url 'blog:compartilhar_postagens' post.id %}">Compartilhar a postagem </a>
</p>

{% with comentarios.count as total_comentarios %}
<h2> {{ total_comentarios}} comentado por {{ total_comentarios|pluralize}}</h2>
{% endwith %}
{% for comentario in comentarios %}
<div class="info">
    <p class="info">
        Comentario {{ forloop.counter }} por {{ comentario.nome}}
        {{ comentario.data_criacao }}
    </p>
    {{ comentario.mensagem|linebreaks }}
</div>
{% empty %}
<p>Não há nenhum comentário</p>
{% if novo_comentario %}
<h2> Seu comentário foi adicionado com sucesso </h2>
{% else %}
<h2>Adicione um novo comentário </h2>
<form method="post">
    {{ formulario_comentario.as_p }}
    {% csrf_token %}
    <p> <input type="submit" value="Adicionar comentário"></p>
</form>
{% endif %}

{% endfor %}

{% endblock %}

blog/templates/blog/postagem/lista.html
{% extends "blog/base.html" %}

{% block title %} Meu blog {% endblock %}

{% block content %}
    <h1> Meu primeiro blog </h1>
    {% for post in posts %}
        <h2> <a href="{{ post.get_absolute_url }}">{{ post.titulo }}</a></h2>

        <p class="data">
            Data da publicação {{ post.data_publicacao }} por {{ post.autor}}
        </p>
        {{ post.mensagem|truncatewords:30|linebreaks}}
    {% endfor%}
        {% include "paginacao.html" with pagina=posts %}
{% endblock %}

blog/templates/paginacao.html
<div class="paginator">
    <span class="'step-links">
        {% if pagina.has_previous %}
            <a href="?page={{ pagina.previous_page_number }}"> Anterior </a>
        {% endif %}

        <span class="current">
            Página {{ pagina.number }} de {{ pagina.paginator.num_pages }}
        </span>
        {% if pagina.has_next %}
        <a href="?page={{ pagina.next_page_number }}">Próxima </a>
        {% endif %}

    </span>

</div>